// Generated by CoffeeScript 1.4.0
(function() {
  var m;

  m = angular.module("zoomlinks", ['ngResource', 'ui']);

  m.factory('Link', function($resource) {
    return $resource('http://zoomlinks.ru/rest/link/:id');
  });

  m.controller('MainCtr', function($scope, Link) {
    return $scope.exportTabs = function() {
      return opera.extension.postMessage('exportTabs');
    };
  });

}).call(this);
