// Generated by CoffeeScript 1.4.0
(function() {
  var m;

  m = angular.module("zoomlinks", ['ngResource', 'ui']);

  m.factory('Link', function($resource) {
    return $resource('http://zoomlinks.ru/rest/link/:id');
  });

  m.controller('MainCtr', function($scope, Link) {
    $scope.exportBookmarks = function() {
      return alert('Hi Opera');
    };
    return $scope.exportTabs = function() {};
  });

}).call(this);
